global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Grafana (requires GF_METRICS_ENABLED=true)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics

  # Promtail metrics (includes our log_entries_total)
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  # cAdvisor (container metrics for ALL containers)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
